### PR TITLE
First Draft

### PR DESCRIPTION
**Pull request by scottcreynolds**
And this one

### CODE REVIEW

**Comment by scottcreynolds** [comment]
@AnnJohn

**Comment by AnnJohn** [comment]
thanks!

**Comment by scottcreynolds** [comment]
:( Can't seem to find the offending snippet.  Is there a way to get more info out of the linter?

**Comment by AnnJohn** [comment]
there isn't more info than that, but I can't find it either in your Readme. Don't worry too much if you can't find it!

**Comment by AnnJohn** [comment]
@scottcreynolds so yes, don't worry about that failure. we didn't have the linter check for erb code snippet so that explains the failure. We'll add that check today. Thanks!

**Comment by blake41** [comment]
scott is crushing it, this is perfect

**Pull request merged**
